# Generated by Django 3.2.6 on 2021-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZINC_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zinc_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
