# Generated by Django 3.2.6 on 2021-08-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210807_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZINC_DB',
        ),
    ]
