# Generated by Django 3.2.6 on 2021-08-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_zinc_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZINC_DB',
        ),
    ]
