# Generated by Django 3.2.6 on 2021-08-07 04:40

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0009_delete_zinc_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZINC_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zinc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('molecule', django_rdkit.models.fields.MolField(null=True)),
                ('atom_count', models.IntegerField(null=True)),
                ('bond_count', models.IntegerField(null=True)),
            ],
        ),
    ]
