# Generated by Django 3.2.6 on 2021-08-07 07:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_zinc_db'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zinc_db',
            index=django.contrib.postgres.indexes.GistIndex(fields=['molecule'], name='database_zi_molecul_d89154_gist'),
        ),
    ]
