# Generated by Django 3.2.6 on 2021-08-07 23:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_add_compound_fingerprint_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zinc_db',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='database_zi_mfp2_c06414_gist'),
        ),
    ]
