# Generated by Django 3.2.6 on 2021-08-08 00:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_create_compound_mfp2_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZINC_DB',
            new_name='Compound',
        ),
        migrations.RemoveIndex(
            model_name='compound',
            name='database_zi_molecul_d89154_gist',
        ),
        migrations.RemoveIndex(
            model_name='compound',
            name='database_zi_mfp2_c06414_gist',
        ),
        migrations.AddIndex(
            model_name='compound',
            index=django.contrib.postgres.indexes.GistIndex(fields=['molecule'], name='database_co_molecul_765fde_gist'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='database_co_mfp2_c5d568_gist'),
        ),
    ]
