# Generated by Django 3.2.6 on 2021-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_rename_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='inchi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
