# Generated by Django 3.2.6 on 2021-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_compound_inchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='inchikey',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
